const groups = [
  {
    label: "basic",
    keycodes: [
      {
        name: "",
        code: "KC_NO",
        byte: 0,
        title: "Nothing",
      },
      {
        name: "▽",
        code: "KC_TRNS",
        byte: 1,
        title: "Pass-through",
      },
      {
        name: "A",
        code: "KC_A",
        byte: 4,
      },
      {
        name: "B",
        code: "KC_B",
        byte: 5,
      },
      {
        name: "C",
        code: "KC_C",
        byte: 6,
      },
      {
        name: "D",
        code: "KC_D",
        byte: 7,
      },
      {
        name: "E",
        code: "KC_E",
        byte: 8,
      },
      {
        name: "F",
        code: "KC_F",
        byte: 9,
      },
      {
        name: "G",
        code: "KC_G",
        byte: 10,
      },
      {
        name: "H",
        code: "KC_H",
        byte: 11,
      },
      {
        name: "I",
        code: "KC_I",
        byte: 12,
      },
      {
        name: "J",
        code: "KC_J",
        byte: 13,
      },
      {
        name: "K",
        code: "KC_K",
        byte: 14,
      },
      {
        name: "L",
        code: "KC_L",
        byte: 15,
      },
      {
        name: "M",
        code: "KC_M",
        byte: 16,
      },
      {
        name: "N",
        code: "KC_N",
        byte: 17,
      },
      {
        name: "O",
        code: "KC_O",
        byte: 18,
      },
      {
        name: "P",
        code: "KC_P",
        byte: 19,
      },
      {
        name: "Q",
        code: "KC_Q",
        byte: 20,
      },
      {
        name: "R",
        code: "KC_R",
        byte: 21,
      },
      {
        name: "S",
        code: "KC_S",
        byte: 22,
      },
      {
        name: "T",
        code: "KC_T",
        byte: 23,
      },
      {
        name: "U",
        code: "KC_U",
        byte: 24,
      },
      {
        name: "V",
        code: "KC_V",
        byte: 25,
      },
      {
        name: "W",
        code: "KC_W",
        byte: 26,
      },
      {
        name: "X",
        code: "KC_X",
        byte: 27,
      },
      {
        name: "Y",
        code: "KC_Y",
        byte: 28,
      },
      {
        name: "Z",
        code: "KC_Z",
        byte: 29,
      },
      {
        name: "!<br/>1",
        code: "KC_1",
        byte: 30,
      },
      {
        name: "@<br/>2",
        code: "KC_2",
        byte: 31,
      },
      {
        name: "#<br/>3",
        code: "KC_3",
        byte: 32,
      },
      {
        name: "$<br/>4",
        code: "KC_4",
        byte: 33,
      },
      {
        name: "%<br/>5",
        code: "KC_5",
        byte: 34,
      },
      {
        name: "^<br/>6",
        code: "KC_6",
        byte: 35,
      },
      {
        name: "&<br/>7",
        code: "KC_7",
        byte: 36,
      },
      {
        name: "*<br/>8",
        code: "KC_8",
        byte: 37,
      },
      {
        name: "(<br/>9",
        code: "KC_9",
        byte: 38,
      },
      {
        name: ")<br/>0",
        code: "KC_0",
        byte: 39,
      },
      {
        name: "Enter",
        code: "KC_ENT",
        byte: 40,
      },
      {
        name: "Esc",
        code: "KC_ESC",
        byte: 41,
      },
      {
        name: "Backspace",
        code: "KC_BSPC",
        byte: 42,
      },
      {
        name: "Tab",
        code: "KC_TAB",
        byte: 43,
      },
      {
        name: "Space",
        code: "KC_SPC",
        byte: 44,
      },
      {
        name: "_<br/>-",
        code: "KC_MINS",
        byte: 45,
      },
      {
        name: "+<br/>=",
        code: "KC_EQL",
        byte: 46,
      },
      {
        name: "{<br/>[",
        code: "KC_LBRC",
        byte: 47,
      },
      {
        name: "}<br/>]",
        code: "KC_RBRC",
        byte: 48,
      },
      {
        name: "|<br/>\\",
        code: "KC_BSLS",
        byte: 49,
      },
      {
        name: ":<br/>;",
        code: "KC_SCLN",
        byte: 51,
      },
      {
        name: "\"<br/>'",
        code: "KC_QUOT",
        byte: 52,
      },
      {
        name: "~<br/>`",
        code: "KC_GRV",
        byte: 53,
      },
      {
        name: "<<br/>,",
        code: "KC_COMM",
        byte: 54,
      },
      {
        name: "><br/>.",
        code: "KC_DOT",
        byte: 55,
      },
      {
        name: "?<br/>/",
        code: "KC_SLSH",
        byte: 56,
      },
      {
        name: "Caps Lock",
        code: "KC_CAPS",
        byte: 57,
      },
      {
        name: "F1",
        code: "KC_F1",
        byte: 58,
      },
      {
        name: "F2",
        code: "KC_F2",
        byte: 59,
      },
      {
        name: "F3",
        code: "KC_F3",
        byte: 60,
      },
      {
        name: "F4",
        code: "KC_F4",
        byte: 61,
      },
      {
        name: "F5",
        code: "KC_F5",
        byte: 62,
      },
      {
        name: "F6",
        code: "KC_F6",
        byte: 63,
      },
      {
        name: "F7",
        code: "KC_F7",
        byte: 64,
      },
      {
        name: "F8",
        code: "KC_F8",
        byte: 65,
      },
      {
        name: "F9",
        code: "KC_F9",
        byte: 66,
      },
      {
        name: "F10",
        code: "KC_F10",
        byte: 67,
      },
      {
        name: "F11",
        code: "KC_F11",
        byte: 68,
      },
      {
        name: "F12",
        code: "KC_F12",
        byte: 69,
      },
      {
        name: "Print<br/>Screen",
        short: "Print",
        code: "KC_PSCR",
        byte: 70,
      },
      {
        name: "Scroll<br/>Lock",
        code: "KC_SLCK",
        short: "Scroll",
        byte: 71,
        title: "Scroll Lock, Brightness Down (macOS)",
      },
      {
        name: "Pause",
        code: "KC_PAUS",
        byte: 72,
      },
      {
        name: "Insert",
        code: "KC_INS",
        byte: 73,
        short: "Ins",
      },
      {
        name: "Home",
        code: "KC_HOME",
        byte: 74,
      },
      {
        name: "Page<br/>Up",
        code: "KC_PGUP",
        byte: 75,
        short: "PgUp",
      },
      {
        name: "Del",
        code: "KC_DEL",
        byte: 76,
        title: "Forward Delete",
      },
      {
        name: "End",
        code: "KC_END",
        byte: 77,
      },
      {
        name: "Page<br/>Down",
        code: "KC_PGDN",
        byte: 78,
        short: "PgDn",
      },
      {
        name: "→",
        code: "KC_RGHT",
        byte: 79,
      },
      {
        name: "←",
        code: "KC_LEFT",
        byte: 80,
      },
      {
        name: "↓",
        code: "KC_DOWN",
        byte: 81,
      },
      {
        name: "↑",
        code: "KC_UP",
        byte: 82,
      },
      {
        name: "Menu",
        code: "KC_APP",
        byte: 101,
      },
      {
        name: "Left Ctrl",
        code: "KC_LCTL",
        byte: 224,
        short: "LCtrl",
      },
      {
        name: "Left Shift",
        code: "KC_LSFT",
        byte: 225,
        short: "LShift",
      },
      {
        name: "Left Alt",
        code: "KC_LALT",
        byte: 226,
        short: "LAlt",
      },
      {
        name: "Left Win",
        code: "KC_LGUI",
        byte: 227,
        short: "LWin",
      },
      {
        name: "Right Ctrl",
        code: "KC_RCTL",
        byte: 228,
        short: "RCtl",
      },
      {
        name: "Right Shift",
        code: "KC_RSFT",
        byte: 229,
        short: "RShft",
      },
      {
        name: "Right Alt",
        code: "KC_RALT",
        byte: 230,
        short: "RAlt",
      },
      {
        name: "Right Win",
        code: "KC_RGUI",
        byte: 231,
        short: "RWin",
      },
    ],
  },
  {
    label: "numpad",
    keycodes: [
      {
        name: "Num<br/>Lock",
        code: "KC_NLCK",
        byte: 83,
        short: "N.Lck",
      },
      {
        name: "/",
        code: "KC_PSLS",
        byte: 84,
        title: "Numpad /",
      },
      {
        name: "*",
        code: "KC_PAST",
        byte: 85,
        title: "Numpad *",
      },
      {
        name: "-",
        code: "KC_PMNS",
        byte: 86,
        title: "Numpad -",
      },
      {
        name: "+",
        code: "KC_PPLS",
        byte: 87,
        title: "Numpad +",
      },
      {
        name: "Numpad Enter",
        short: "N.Ent",
        code: "KC_PENT",
        byte: 88,
        title: "Numpad Enter",
      },
      {
        name: "1",
        code: "KC_P1",
        byte: 89,
        title: "Numpad 1",
      },
      {
        name: "2",
        code: "KC_P2",
        byte: 90,
        title: "Numpad 2",
      },
      {
        name: "3",
        code: "KC_P3",
        byte: 91,
        title: "Numpad 3",
      },
      {
        name: "4",
        code: "KC_P4",
        byte: 92,
        title: "Numpad 4",
      },
      {
        name: "5",
        code: "KC_P5",
        byte: 93,
        title: "Numpad 5",
      },
      {
        name: "6",
        code: "KC_P6",
        byte: 94,
        title: "Numpad 6",
      },
      {
        name: "7",
        code: "KC_P7",
        byte: 95,
        title: "Numpad 7",
      },
      {
        name: "8",
        code: "KC_P8",
        byte: 96,
        title: "Numpad 8",
      },
      {
        name: "9",
        code: "KC_P9",
        byte: 97,
        title: "Numpad 9",
      },
      {
        name: "0",
        code: "KC_P0",
        byte: 98,
        title: "Numpad 0",
      },
      {
        name: ".",
        code: "KC_PDOT",
        byte: 99,
        title: "Numpad .",
      },
    ],
  },
  {
    label: "media",
    keycodes: [
      {
        name: "Mute",
        code: "KC_MUTE",
        byte: 168,
        title: "Mute Audio",
      },
      {
        name: "Vol+",
        code: "KC_VOLU",
        byte: 169,
        title: "Volume Up",
      },
      {
        name: "Vol-",
        code: "KC_VOLD",
        byte: 170,
        title: "Volume Down",
      },
      {
        name: "Next",
        code: "KC_MNXT",
        byte: 171,
        title: "Media Next",
      },
      {
        name: "Prev",
        code: "KC_MPRV",
        byte: 172,
        title: "Media Previous",
      },
      {
        name: "Media<br/>Stop",
        code: "KC_MSTP",
        byte: 173,
        title: "Media Stop",
      },
      {
        name: "Play",
        code: "KC_MPLY",
        byte: 174,
        title: "Play/Pause",
      },
      {
        name: "Select",
        code: "KC_MSEL",
        byte: 175,
        title: "Media Select",
      },
      {
        name: "Eject",
        code: "KC_EJCT",
        byte: 176,
        title: "Media Eject",
      },
      {
        name: "Next<br/>Track",
        code: "KC_MFFD",
        byte: 187,
        title: "Fast Forward",
      },
      {
        name: "Prev<br/>Track",
        code: "KC_MRWD",
        byte: 188,
        title: "Rewind",
      },
    ],
  },
  {
    label: "layer",
    keycodes: [
      {
        name: "Fn1<br/>(Fn3)",
        code: "FN_MO13",
        byte: 24336,
        title: "Hold = layer1, Hold with Fn2 = layer3",
      },
      {
        name: "Fn2<br/>(Fn3)",
        code: "FN_MO23",
        byte: 24337,
        title: "Hold = layer2, Hold with Fn1 = layer3",
      },
      {
        name: "Space<br/>Fn1",
        code: "SPC_FN1",
        byte: 16684,
        title: "Hold = layer1, Tap = Space",
      },
      {
        name: "Space<br/>Fn2",
        code: "SPC_FN2",
        byte: 16940,
        title: "Hold = layer2, Tap = Space",
      },
      {
        name: "Space<br/>Fn3",
        code: "SPC_FN3",
        byte: 17196,
        title: "Hold = layer3, Tap = Space",
      },
      {
        name: "TO(0)",
        code: "TO(0)",
        title: "Turn on layer0 when pressed",
        byte: 20496,
      },
      {
        name: "TO(1)",
        code: "TO(1)",
        title: "Turn on layer1 when pressed",
        byte: 20497,
      },
      {
        name: "TO(2)",
        code: "TO(2)",
        title: "Turn on layer2 when pressed",
        byte: 20498,
      },
      {
        name: "TO(3)",
        code: "TO(3)",
        title: "Turn on layer3 when pressed",
        byte: 20499,
      },
      {
        name: "MO(0)",
        code: "MO(0)",
        title: "Momentary turn layer0 on",
        byte: 20736,
      },
      {
        name: "MO(1)",
        code: "MO(1)",
        title: "Momentary turn layer1 on",
        byte: 20737,
      },
      {
        name: "MO(2)",
        code: "MO(2)",
        title: "Momentary turn layer2 on",
        byte: 20738,
      },
      {
        name: "MO(3)",
        code: "MO(3)",
        title: "Momentary turn layer3 on",
        byte: 20739,
      },
      {
        name: "TG(0)",
        code: "TG(0)",
        title: "Toggle layer0 on/off",
        byte: 21248,
      },
      {
        name: "TG(1)",
        code: "TG(1)",
        title: "Toggle layer1 on/off",
        byte: 21249,
      },
      {
        name: "TG(2)",
        code: "TG(2)",
        title: "Toggle layer2 on/off",
        byte: 21250,
      },
      {
        name: "TG(3)",
        code: "TG(3)",
        title: "Toggle layer3 on/off",
        byte: 21251,
      },
      {
        name: "OSL(0)",
        code: "OSL(0)",
        title: "Switch to layer0 for one keypress",
        byte: 21504,
      },
      {
        name: "OSL(1)",
        code: "OSL(1)",
        title: "Switch to layer1 for one keypress",
        byte: 21505,
      },
      {
        name: "OSL(2)",
        code: "OSL(2)",
        title: "Switch to layer2 for one keypress",
        byte: 21506,
      },
      {
        name: "OSL(3)",
        code: "OSL(3)",
        title: "Switch to layer3 for one keypress",
        byte: 21507,
      },
      {
        name: "TT(0)",
        code: "TT(0)",
        title:
          "Normally acts like MO unless it's tapped multple times which toggles layer0 on",
        byte: 22528,
      },
      {
        name: "TT(1)",
        code: "TT(1)",
        title:
          "Normally acts like MO unless it's tapped multple times which toggles layer1 on",
        byte: 22529,
      },
      {
        name: "TT(2)",
        code: "TT(2)",
        title:
          "Normally acts like MO unless it's tapped multple times which toggles layer2 on",
        byte: 22530,
      },
      {
        name: "TT(3)",
        code: "TT(3)",
        title:
          "Normally acts like MO unless it's tapped multple times which toggles layer3 on",
        byte: 22531,
      },
    ],
  },
  {
    label: "light",
    keycodes: [
      {
        name: "BL<br/>Togg",
        code: "BL_TOGG",
        byte: 23743,
        title: "Turn the backlight on or off",
      },
      {
        name: "BL On",
        code: "BL_ON",
        byte: 23739,
        title: "Set the backlight to max brightness",
      },
      {
        name: "BL Off",
        code: "BL_OFF",
        byte: 23740,
        title: "Turn the backlight off",
      },
      {
        name: "BL -",
        code: "BL_DEC",
        byte: 23741,
        title: "Decrease the backlight level",
      },
      {
        name: "BL +",
        code: "BL_INC",
        byte: 23742,
        title: "Increase the backlight level",
      },
      {
        name: "EF -",
        code: "EF_DEC",
        byte: 24323,
        title: "Effect -",
      },
      {
        name: "EF +",
        code: "EF_INC",
        byte: 24322,
        title: "Effect +",
      },
      {
        name: "ES -",
        code: "ES_DEC",
        byte: 24325,
        title: "Effect Speed -",
      },
      {
        name: "ES +",
        code: "ES_INC",
        byte: 24324,
        title: "Effect Speed +",
      },
      {
        name: "H1 -",
        code: "H1_DEC",
        byte: 24327,
        title: "Color1 Hue -",
      },
      {
        name: "H1 +",
        code: "H1_INC",
        byte: 24326,
        title: "Color1 Hue +",
      },
      {
        name: "H2 -",
        code: "H2_DEC",
        byte: 24331,
        title: "Color2 Hue -",
      },
      {
        name: "H2 +",
        code: "H2_INC",
        byte: 24330,
        title: "Color2 Hue +",
      },
      {
        name: "S1 -",
        code: "S1_DEC",
        byte: 24329,
        title: "Color1 Sat -",
      },
      {
        name: "S1 +",
        code: "S1_INC",
        byte: 24328,
        title: "Color1 Sat +",
      },
      {
        name: "S2 -",
        code: "S2_DEC",
        byte: 24333,
        title: "Color2 Sat -",
      },
      {
        name: "S2 +",
        code: "S2_INC",
        byte: 24332,
        title: "Color2 Sat +",
      },
      {
        name: "BL<br/>Cycle",
        code: "BL_STEP",
        byte: 23744,
        title: "Cycle through backlight levels",
      },
      {
        name: "BR<br/>Togg",
        code: "BL_BRTG",
        byte: 23745,
        title: "Toggle backlight breathing",
      },
      {
        name: "RGB<br/>Togg",
        code: "RGB_TOG",
        byte: 23746,
        title: "Toggle RGB lighting on or off",
      },
      {
        name: "RGB<br/>Mode-",
        short: "RGB<br/>MD-",
        code: "RGB_RMOD",
        byte: 23748,
        title:
          "Cycle through modes in reverse, forward direction when Shift is held",
      },
      {
        name: "RGB<br/>Mode+",
        short: "RGB<br/>MD+",
        code: "RGB_MOD",
        byte: 23747,
        title: "Cycle through modes, reverse direction when Shift is held",
      },
      {
        name: "Hue -",
        code: "RGB_HUD",
        byte: 23750,
        title: "Decrease hue, increase hue when Shift is held",
      },
      {
        name: "Hue +",
        code: "RGB_HUI",
        byte: 23749,
        title: "Increase hue, decrease hue when Shift is held",
      },
      {
        name: "Sat -",
        code: "RGB_SAD",
        byte: 23752,
        title: "Decrease saturation, increase saturation when Shift is held",
      },
      {
        name: "Sat +",
        code: "RGB_SAI",
        byte: 23751,
        title: "Increase saturation, decrease saturation when Shift is held",
      },
      {
        name: "Bright -",
        code: "RGB_VAD",
        byte: 23754,
        title: "Decrease value (brightness), increase value when Shift is held",
      },
      {
        name: "Bright +",
        code: "RGB_VAI",
        byte: 23753,
        title: "Increase value (brightness), decrease value when Shift is held",
      },
      {
        name: "Effect Speed -",
        short: "Effect<br/>SP -",
        code: "RGB_SPD",
        byte: 23756,
        title:
          "Decrease effect speed (does not support eeprom yet), increase speed when Shift is held",
      },
      {
        name: "Effect Speed +",
        short: "Effect<br/>SP +",
        code: "RGB_SPI",
        byte: 23755,
        title:
          "Increase effect speed (does not support eeprom yet), decrease speed when Shift is held",
      },
      {
        name: "RGB Mode P",
        short: "RGB P",
        code: "RGB_M_P",
        byte: 23757,
        title: "Plain",
      },
      {
        name: "RGB Mode B",
        short: "RGB B",
        code: "RGB_M_B",
        byte: 23758,
        title: "Breathe",
      },
      {
        name: "RGB Mode R",
        short: "RGB R",
        code: "RGB_M_R",
        byte: 23759,
        title: "Rainbow",
      },
      {
        name: "RGB Mode SW",
        short: "RGB SW",
        code: "RGB_M_SW",
        byte: 23760,
        title: "Swirl",
      },
      {
        name: "RGB Mode SN",
        short: "RGB SN",
        code: "RGB_M_SN",
        byte: 23761,
        title: "Snake",
      },
      {
        name: "RGB Mode K",
        short: "RGB K",
        code: "RGB_M_K",
        byte: 23762,
        title: "Knight",
      },
      {
        name: "RGB Mode X",
        short: "RGB X",
        code: "RGB_M_X",
        byte: 23763,
        title: "Xmas",
      },
      {
        name: "RGB Mode G",
        short: "RGB G",
        code: "RGB_M_G",
        byte: 23764,
        title: "Gradient",
      },
    ],
  },
  {
    label: "macro",
    keycodes: Array.from({ length: 16 }, (_, i) => ({
      name: `MA${i}`,
      code: `MACRO${i}`,
      byte: 24338 + i,
    })),
  },
  {
    label: "hyper",
    keycodes: [
      {
        name: "=",
        code: "KC_PEQL",
        byte: 103,
      },
      {
        name: ",",
        code: "KC_PCMM",
        byte: 133,
      },
      {
        name: "~",
        code: "KC_TILD",
        byte: 565,
      },
      {
        name: "!",
        code: "KC_EXLM",
        byte: 542,
      },
      {
        name: "@",
        code: "KC_AT",
        byte: 543,
      },
      {
        name: "#",
        code: "KC_HASH",
        byte: 544,
      },
      {
        name: "$",
        code: "KC_DLR",
        byte: 545,
      },
      {
        name: "%",
        code: "KC_PERC",
        byte: 546,
      },
      {
        name: "^",
        code: "KC_CIRC",
        byte: 547,
      },
      {
        name: "&",
        code: "KC_AMPR",
        byte: 548,
      },
      {
        name: "*",
        code: "KC_ASTR",
        byte: 549,
      },
      {
        name: "(",
        code: "KC_LPRN",
        byte: 550,
      },
      {
        name: ")",
        code: "KC_RPRN",
        byte: 551,
      },
      {
        name: "_",
        code: "KC_UNDS",
        byte: 557,
      },
      {
        name: "+",
        code: "KC_PLUS",
        byte: 558,
      },
      {
        name: "{",
        code: "KC_LCBR",
        byte: 559,
      },
      {
        name: "}",
        code: "KC_RCBR",
        byte: 560,
      },
      {
        name: "<",
        code: "KC_LT",
        byte: 566,
      },
      {
        name: ">",
        code: "KC_GT",
        byte: 567,
      },
      {
        name: ":",
        code: "KC_COLN",
        byte: 563,
      },
      {
        name: "|",
        code: "KC_PIPE",
        byte: 561,
      },
      {
        name: "?",
        code: "KC_QUES",
        byte: 568,
      },
      {
        name: '"',
        code: "KC_DQUO",
        byte: 564,
      },
      {
        name: "NUHS",
        code: "KC_NUHS",
        byte: 50,
        title: "Non-US # and ~",
      },
      {
        name: "NUBS",
        code: "KC_NUBS",
        byte: 100,
        title: "Non-US \\ and |",
      },
      {
        name: "Ro",
        code: "KC_RO",
        byte: 135,
        title: "JIS \\ and |",
      },
      {
        name: "¥",
        code: "KC_JYEN",
        byte: 137,
        title: "JPN Yen",
      },
      {
        name: "無変換",
        code: "KC_MHEN",
        byte: 139,
        title: "JIS Muhenkan",
      },
      {
        name: "漢字",
        code: "KC_HANJ",
        byte: 145,
        title: "Hanja",
      },
      {
        name: "한영",
        code: "KC_HAEN",
        byte: 144,
        title: "HanYeong",
      },
      {
        name: "変換",
        code: "KC_HENK",
        byte: 138,
        title: "JIS Henkan",
      },
      {
        name: "かな",
        code: "KC_KANA",
        byte: 136,
        title: "JIS Katakana/Hiragana",
      },
      {
        name: "Reset",
        code: "RESET",
        byte: 23552,
        title: "Reset the keyboard",
      },
      {
        name: "Esc `",
        code: "KC_GESC",
        byte: 23574,
        title: "Esc normally, but ` when Shift or Win is pressed",
      },
      {
        name: "LC (",
        code: "KC_LCPO",
        byte: 23795,
        title: "Left Shift when held, ( when tapped",
      },
      {
        name: "RC )",
        code: "KC_RCPC",
        byte: 23796,
        title: "Right Shift when held, ) when tapped",
      },
      {
        name: "LS (",
        code: "KC_LSPO",
        byte: 23767,
      },
      {
        name: "RS )",
        code: "KC_RSPC",
        byte: 23768,
      },
      {
        name: "LA (",
        code: "KC_LAPO",
        byte: 23797,
        title: "Left Alt when held, ( when tapped",
      },
      {
        name: "RA )",
        code: "KC_RAPC",
        byte: 23798,
        title: "Right Alt when held, ) when tapped",
      },
      {
        name: "Debug",
        code: "DEBUG",
        byte: 23553,
        title: "Toggle debug mode",
      },
      {
        name: "Shift<br/>Enter",
        code: "KC_SFTENT",
        byte: 23769,
        title: "Right Shift when held, Enter when tapped",
      },
      {
        name: "NKRO",
        code: "MAGIC_TOGGLE_NKRO",
        byte: 23572,
        title: "Toggle NKRO",
      },
      {
        name: "Screen +",
        code: "KC_BRIU",
        short: "Scr +",
        title: "Screen Brightness Up",
        byte: 189,
      },
      {
        name: "Screen -",
        code: "KC_BRID",
        short: "Scr -",
        title: "Screen Brightness Down",
        byte: 190,
      },
      {
        name: "F13",
        code: "KC_F13",
        byte: 104,
      },
      {
        name: "F14",
        code: "KC_F14",
        byte: 105,
      },
      {
        name: "F15",
        code: "KC_F15",
        byte: 106,
      },
      {
        name: "F16",
        code: "KC_F16",
        byte: 107,
      },
      {
        name: "F17",
        code: "KC_F17",
        byte: 108,
      },
      {
        name: "F18",
        code: "KC_F18",
        byte: 109,
      },
      {
        name: "F19",
        code: "KC_F19",
        byte: 110,
      },
      {
        name: "F20",
        code: "KC_F20",
        byte: 111,
      },
      {
        name: "F21",
        code: "KC_F21",
        byte: 112,
      },
      {
        name: "F22",
        code: "KC_F22",
        byte: 113,
      },
      {
        name: "F23",
        code: "KC_F23",
        byte: 114,
      },
      {
        name: "F24",
        code: "KC_F24",
        byte: 115,
      },
      {
        name: "Exec",
        code: "KC_EXECUTE",
        byte: 116,
      },
      {
        name: "Help",
        code: "KC_HELP",
        byte: 117,
      },
      {
        name: "Menu",
        code: "KC_MENU",
        byte: 118,
      },
      {
        name: "Select",
        code: "KC_SELECT",
        byte: 119,
      },
      {
        name: "Stop",
        code: "KC_STOP",
        byte: 120,
      },
      {
        name: "Again",
        code: "KC_AGAIN",
        byte: 121,
      },
      {
        name: "Undo",
        code: "KC_UNDO",
        byte: 122,
      },
      {
        name: "Find",
        code: "KC_FIND",
        byte: 126,
      },
      {
        name: "Locking Caps Lock",
        short: "Lock<br/>Caps",
        code: "KC_LCAP",
        byte: 130,
      },
      {
        name: "Locking Num Lock",
        short: "Lock<br/>Num",
        code: "KC_LNUM",
        byte: 131,
      },
      {
        name: "Locking Scroll Lock",
        short: "Lock<br/>Scroll",
        code: "KC_LSCR",
        byte: 132,
      },
      {
        name: "Power<br/>OSX",
        code: "KC_POWER",
        byte: 102,
        title: "System Power",
      },
      {
        name: "Power",
        code: "KC_PWR",
        byte: 165,
        title: "System Power Down",
      },
      {
        name: "Sleep",
        code: "KC_SLEP",
        byte: 166,
        title: "System Sleep",
      },
      {
        name: "Wake",
        code: "KC_WAKE",
        byte: 167,
        title: "System Wake",
      },
      {
        name: "Mail",
        code: "KC_MAIL",
        byte: 177,
        title: "Launch Mail",
      },
      {
        name: "Calc",
        code: "KC_CALC",
        byte: 178,
        title: "Launch Calculator",
      },
      // {
      //   name: 'My<br/>Comp',
      //   code: 'KC_MYCM',
      //   byte: 179,
      //   title: 'Mouse Cursor Up',
      // },
      {
        name: "Mouse ↑",
        short: "MS ↑",
        code: "KC_MS_UP",
        byte: 240,
      },
      {
        name: "Mouse ↓",
        short: "MS ↓",
        code: "KC_MS_DOWN",
        byte: 241,
        title: "Mouse Cursor Down",
      },
      {
        name: "Mouse ←",
        short: "MS ←",
        code: "KC_MS_LEFT",
        byte: 242,
        title: "Mouse Cursor Left",
      },
      {
        name: "Mouse →",
        short: "MS →",
        code: "KC_MS_RIGHT",
        byte: 243,
        title: "Mouse Cursor Right",
      },
      {
        name: "Mouse<br/>Btn1",
        code: "KC_MS_BTN1",
        byte: 244,
        title: "Mouse Button 1",
      },
      {
        name: "Mouse<br/>Btn2",
        code: "KC_MS_BTN2",
        byte: 245,
        title: "Mouse Button 2",
      },
      {
        name: "Mouse<br/>Btn3",
        code: "KC_MS_BTN3",
        byte: 246,
        title: "Mouse Button 3",
      },
      {
        name: "Mouse<br/>Btn4",
        code: "KC_MS_BTN4",
        byte: 247,
        title: "Mouse Button 4",
      },
      {
        name: "Mouse<br/>Btn5",
        code: "KC_MS_BTN5",
        byte: 248,
        title: "Mouse Button 5",
      },
      {
        name: "Mouse<br/>WH↑",
        code: "KC_MS_WH_UP",
        byte: 249,
        title: "Mouse Wheel Down",
      },
      {
        name: "Mouse<br/>WH↓",
        code: "KC_MS_WH_DOWN",
        byte: 250,
      },
      {
        name: "Mouse<br/>WH←",
        code: "KC_MS_WH_LEFT",
        byte: 251,
        title: "Mouse Wheel Left",
      },
      {
        name: "Mouse<br/>WH→",
        code: "KC_MS_WH_RIGHT",
        byte: 252,
        title: "Mouse Wheel Right",
      },
      {
        name: "Mouse<br/>Acc0",
        code: "KC_MS_ACCEL0",
        byte: 253,
        title: "Set mouse acceleration to 0",
      },
      {
        name: "Mouse<br/>Acc1",
        code: "KC_MS_ACCEL1",
        byte: 254,
        title: "Set mouse acceleration to 1",
      },
      {
        name: "Mouse<br/>Acc2",
        code: "KC_MS_ACCEL2",
        byte: 255,
        title: "Set mouse acceleration to 2",
      },
    ],
  },
  {
    label: "bluetooth",
    keycodes: [
      {
        name: "BLE0",
        code: "KC_BLE_0",
        byte: 32768,
      },
      {
        name: "BLE1",
        code: "KC_BLE_1",
        byte: 32769,
      },
      {
        name: "BLE2",
        code: "KC_BLE_2",
        byte: 32770,
      },
      {
        name: "BLE<br/>Reset",
        code: "KC_BLE_RESET",
        byte: 33023,
      },
    ],
  },
];

const macroKeys = [
  "KC_NO",
  "KC_A",
  "KC_B",
  "KC_C",
  "KC_D",
  "KC_E",
  "KC_F",
  "KC_G",
  "KC_H",
  "KC_I",
  "KC_J",
  "KC_K",
  "KC_L",
  "KC_M",
  "KC_N",
  "KC_O",
  "KC_P",
  "KC_Q",
  "KC_R",
  "KC_S",
  "KC_T",
  "KC_U",
  "KC_V",
  "KC_W",
  "KC_X",
  "KC_Y",
  "KC_Z",
  "KC_1",
  "KC_2",
  "KC_3",
  "KC_4",
  "KC_5",
  "KC_6",
  "KC_7",
  "KC_8",
  "KC_9",
  "KC_0",
  "KC_ENT",
  "KC_ESC",
  "KC_BSPC",
  "KC_TAB",
  "KC_SPC",
  "KC_MINS",
  "KC_EQL",
  "KC_LBRC",
  "KC_RBRC",
  "KC_BSLS",
  "KC_NUHS",
  "KC_SCLN",
  "KC_QUOT",
  "KC_GRV",
  "KC_COMM",
  "KC_DOT",
  "KC_SLSH",
  "KC_CAPS",
  "KC_F1",
  "KC_F2",
  "KC_F3",
  "KC_F4",
  "KC_F5",
  "KC_F6",
  "KC_F7",
  "KC_F8",
  "KC_F9",
  "KC_F10",
  "KC_F11",
  "KC_F12",
  "KC_PSCR",
  "KC_SLCK",
  "KC_PAUS",
  "KC_INS",
  "KC_HOME",
  "KC_PGUP",
  "KC_DEL",
  "KC_END",
  "KC_PGDN",
  "KC_RGHT",
  "KC_LEFT",
  "KC_DOWN",
  "KC_UP",
  "KC_NLCK",
  "KC_PSLS",
  "KC_KP_ASTERISK",
  "KC_PAST",
  "KC_PPLS",
  "KC_PENT",
  "KC_P1",
  "KC_P2",
  "KC_P3",
  "KC_P4",
  "KC_P5",
  "KC_P6",
  "KC_P7",
  "KC_P8",
  "KC_P9",
  "KC_P0",
  "KC_PDOT",
  "KC_NUBS",
  "KC_APP",
  "KC_POWER",
  "KC_PEQL",
  "KC_F13",
  "KC_F14",
  "KC_F15",
  "KC_F16",
  "KC_F17",
  "KC_F18",
  "KC_F19",
  "KC_F20",
  "KC_F21",
  "KC_F22",
  "KC_F23",
  "KC_F24",
  "KC_EXECUTE",
  "KC_HELP",
  "KC_MENU",
  "KC_SELECT",
  "KC_STOP",
  "KC_AGAIN",
  "KC_UNDO",
  "KC_CUT",
  "KC_COPY",
  "KC_PASTE",
  "KC_FIND",
  "KC_LCAP",
  "KC_LNUM",
  "KC_LSCR",
  "KC_PCMM",
  "KC_KP_EQUAL_AS400",
  "KC_RO",
  "KC_KANA",
  "KC_JYEN",
  "KC_HENK",
  "KC_MHEN",
  "KC_INT6",
  "KC_INT7",
  "KC_INT8",
  "KC_INT9",
  "KC_HAEN",
  "KC_HANJ",
  "KC_LANG3",
  "KC_LANG4",
  "KC_LANG5",
  "KC_LANG6",
  "KC_LANG7",
  "KC_LANG8",
  "KC_LANG9",
  "KC_SYSREQ",
  "KC_CANCEL",
  "KC_CLEAR",
  "KC_PRIOR",
  "KC_OUT",
  "KC_OPER",
  "KC_CLEAR_AGAIN",
  "KC_CRSEL",
  "KC_EXSEL",
  "KC_LCTL",
  "KC_LSFT",
  "KC_LALT",
  "KC_LGUI",
  "KC_RCTL",
  "KC_RSFT",
  "KC_RALT",
  "KC_RGUI",
  "KC_PWR",
  "KC_SLEP",
  "KC_WAKE",
  "KC_MUTE",
  "KC_VOLU",
  "KC_VOLD",
  "KC_MNXT",
  "KC_MPRV",
  "KC_MSTP",
  "KC_MPLY",
  "KC_MSEL",
  "KC_EJCT",
  "KC_MAIL",
  "KC_CALC",
  "KC_MYCM",
  "KC_WWW_SEARCH",
  "KC_WWW_HOME",
  "KC_WWW_BACK",
  "KC_WWW_FORWARD",
  "KC_WWW_STOP",
  "KC_WWW_REFRESH",
  "KC_WWW_FAVORITES",
  "KC_MFFD",
  "KC_MRWD",
];

const modTapKeys = [
  {
    name: "LCtrl",
    code: 0x01,
  },
  {
    name: "LShift",
    code: 0x02,
  },
  {
    name: "LAlt",
    code: 0x04,
  },
  {
    name: "LWin",
    code: 0x08,
  },
  {
    name: "RCtrl",
    code: 0x11,
  },
  {
    name: "RShift",
    code: 0x12,
  },
  {
    name: "RAlt",
    code: 0x14,
  },
  {
    name: "RWin",
    code: 0x18,
  },
];
const modBasicKeys = groups.filter((t) => t.label === "basic")[0]["keycodes"];
module.exports = {
  allKeycodes: groups.reduce((acc, group) => acc.concat(group.keycodes), []),
  basicKeycodes: groups.filter((t) => t.label === "basic")[0],
  numpadKeycodes: groups.filter((t) => t.label === "numpad")[0],
  mediaKeycodes: groups.filter((t) => t.label === "media")[0],
  layerKeycodes: groups.filter((t) => t.label === "layer")[0],
  lightKeycodes: groups.filter((t) => t.label === "light")[0],
  macroKeycodes: groups.filter((t) => t.label === "macro")[0],
  hyperKeycodes: groups.filter((t) => t.label === "hyper")[0],
  // bluetoothKeycodes: groups.filter((t) => t.label === 'bluetooth')[0],
  macroKeys,
  modTapKeys,
  modBasicKeys,
};
